name: Procon-gardener

on:
  schedule:
  - cron: "* */24 * * *"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install procon-gardener
      run: |
        go install github.com/togatoga/procon-gardener@latest
        procon-gardener init

    - name: Create config.json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: config.json
        json: '{"atcoder": {"repository_path": ".", "user_id": "${{ secrets.ATCODER_USERNAME }}", "user_email": "${{ secrets.ATCODER_EMAIL }}"}}'
        dir: '../../../.procon-gardener'

    - name: Archive
      run: procon-gardener archive

    - name: Git push
      run: git push
