name: Procon-gardener

on:
  schedule:
  - cron: "* */24 * * *"
  push:

jobs:

  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install procon-gardener
      run: |
        go install github.com/togatoga/procon-gardener@latest
        procon-gardener init

    - name: Edit config.json
      env:
        ATCODER_USERNAME: ${{ secrets.ATCODER_USERNAME }}
        ATCODER_EMAIL: ${{ secrets.ATCODER_EMAIL }}
      run: |
        cd ../../../.procon-gardener
        jq '.atcoder.repository_path|="."' config.json > tmp
        mv tmp config.json
        jq '.atcoder.user_id|="$ATCODER_USERNAME"' config.json > tmp
        mv tmp config.json
        jq '.atcoder.user_email|="$ATCODER_EMAIL"' config.json > tmp
        mv tmp config.json

    - name: Archive
      run: procon-gardener archive

    - name: Git push
      run: git push
